# Generated by Django 4.2.16 on 2026-09-17 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spare_parts', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('inventory', '0003_delete_serializeddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('imei', 'IMEI Devices'), ('accessory', 'Accessories'), ('spare_part', 'Spare Parts'), ('product', 'Products')], max_length=20)),
                ('product', models.CharField(help_text='Product / part / device name', max_length=255)),
                ('sku', models.CharField(blank=True, help_text='For accessory / spare / product matching & creation', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, help_text='Used when creating new stock', max_digits=12)),
                ('imeis', models.TextField(blank=True)),
                ('applied', models.BooleanField(default=False)),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product')),
                ('linked_spare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spare_parts.sparepart')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.procurement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
