# Generated by Django 4.2.16 on 2026-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='pta_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
