# Generated by Django 4.2.16 on 2026-09-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_procurementitem_condition_procurementitem_pta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='spare_category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
