# Generated by Django 4.2.16 on 2026-09-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_procurementitem_spare_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='low_stock_alert',
            field=models.PositiveIntegerField(blank=True, help_text='Alert when stock falls to or below this quantity (accessory / product / spare part)', null=True),
        ),
    ]
