# Generated by Django 4.2.16 on 2026-09-14 09:42

from django.db import migrations, models

TABLE = 'inventory_serializeddevice'

# Reject a row whose imei1/imei2 collides with EITHER imei column of any OTHER
# row. Per-column unique indexes can't see cross-column collisions (one device's
# imei1 equalling another's imei2), so triggers enforce the full-union rule.
_SQLITE_COLLIDES = """
    EXISTS (
        SELECT 1 FROM {t} d WHERE d.id <> NEW.id AND (
               d.imei1 = NEW.imei1
            OR (NEW.imei2 IS NOT NULL AND d.imei1 = NEW.imei2)
            OR (d.imei2 IS NOT NULL AND d.imei2 = NEW.imei1)
            OR (NEW.imei2 IS NOT NULL AND d.imei2 IS NOT NULL AND d.imei2 = NEW.imei2)
        )
    )
""".format(t=TABLE)


def install_imei_union_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    ex = schema_editor.execute
    if vendor == 'sqlite':
        # NEW.id is unset on INSERT; COALESCE(NEW.id, -1) makes d.id <> NEW.id
        # harmless for inserts (no row can have id -1).
        cond = _SQLITE_COLLIDES.replace('NEW.id', 'COALESCE(NEW.id, -1)')
        for op in ('INSERT', 'UPDATE'):
            ex(f"""
                CREATE TRIGGER {TABLE}_imei_union_{op.lower()}
                BEFORE {op} ON {TABLE}
                WHEN {cond}
                BEGIN
                    SELECT RAISE(ABORT, 'Duplicate IMEI: this IMEI already exists on another device');
                END;
            """)
    elif vendor == 'postgresql':
        ex(f"""
            CREATE OR REPLACE FUNCTION {TABLE}_imei_union_check()
            RETURNS trigger AS $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM {TABLE} d WHERE d.id <> NEW.id AND (
                           d.imei1 = NEW.imei1
                        OR (NEW.imei2 IS NOT NULL AND d.imei1 = NEW.imei2)
                        OR (d.imei2 IS NOT NULL AND d.imei2 = NEW.imei1)
                        OR (NEW.imei2 IS NOT NULL AND d.imei2 IS NOT NULL AND d.imei2 = NEW.imei2)
                    )
                ) THEN
                    RAISE EXCEPTION 'Duplicate IMEI: this IMEI already exists on another device';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)
        ex(f"""
            CREATE TRIGGER {TABLE}_imei_union
            BEFORE INSERT OR UPDATE ON {TABLE}
            FOR EACH ROW EXECUTE FUNCTION {TABLE}_imei_union_check();
        """)


def remove_imei_union_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    ex = schema_editor.execute
    ex(f'DROP TRIGGER IF EXISTS {TABLE}_imei_union_insert;')
    ex(f'DROP TRIGGER IF EXISTS {TABLE}_imei_union_update;')
    if vendor == 'postgresql':
        ex(f'DROP TRIGGER IF EXISTS {TABLE}_imei_union ON {TABLE};')
        ex(f'DROP FUNCTION IF EXISTS {TABLE}_imei_union_check();')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('storage_ram', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('open_box', 'Open Box')], max_length=20)),
                ('warranty_type', models.CharField(max_length=100)),
                ('imei1', models.CharField(max_length=20, unique=True)),
                ('imei2', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='serializeddevice',
            constraint=models.UniqueConstraint(condition=models.Q(('imei2__isnull', False)), fields=('imei2',), name='uniq_serialdevice_imei2'),
        ),
        migrations.AddConstraint(
            model_name='serializeddevice',
            constraint=models.CheckConstraint(check=models.Q(('imei2__isnull', True), models.Q(('imei2', models.F('imei1')), _negated=True), _connector='OR'), name='serialdevice_imei1_ne_imei2'),
        ),
        migrations.RunPython(install_imei_union_guards, remove_imei_union_guards),
    ]
