# Generated by Django 4.2.16 on 2026-09-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_serializeddevice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SerializedDevice',
        ),
    ]
