# Generated by Django 4.2.16 on 2026-09-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_serializeddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Return'), ('repair_use', 'Used in Repair'), ('repair_return', 'Returned from Repair')], max_length=30),
        ),
    ]
