# Generated by Django 4.2.16 on 2026-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='condition',
            field=models.CharField(default='Grade A', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pta_status',
            field=models.CharField(default='PTA Approved', max_length=50),
        ),
    ]
