# Generated by Django 4.2.16 on 2026-08-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Mobile Shop', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('ntn', models.CharField(blank=True, max_length=50, verbose_name='NTN / Tax Number')),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('receipt_footer', models.TextField(blank=True, help_text='Printed at the bottom of receipts')),
                ('logo', models.FileField(blank=True, null=True, upload_to='company/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
