# Generated by Django 4.2.16 on 2026-09-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='settings_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='theme',
            field=models.CharField(choices=[('crimson', 'Crimson'), ('blue', 'Ocean Blue'), ('emerald', 'Emerald'), ('violet', 'Royal Violet'), ('orange', 'Sunset Orange'), ('teal', 'Teal')], default='crimson', max_length=20),
        ),
    ]
