# Generated by Django 4.2.16 on 2026-09-18 16:38

from django.db import migrations, models


DEFAULT_OPTIONS = {
    'pta_status': [('PTA Approved', 'green'), ('Non-PTA', 'yellow'), ('PTA Blocked', 'red')],
    'device_condition': [('Grade A', 'green'), ('Grade B', 'blue'), ('Grade C', 'yellow'),
                         ('Refurbished', 'orange'), ('For Parts', 'red')],
    'payment_method': [('Cash', 'green'), ('Card', 'blue'), ('EasyPaisa', 'green'),
                       ('JazzCash', 'orange'), ('Bank Transfer', 'blue')],
}


def seed_options(apps, schema_editor):
    ChoiceOption = apps.get_model('settings_app', 'ChoiceOption')
    for group, items in DEFAULT_OPTIONS.items():
        for i, (label, color) in enumerate(items):
            ChoiceOption.objects.get_or_create(group=group, label=label,
                                               defaults={'color': color, 'sort_order': i})


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_companysettings_settings_key_companysettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='receipt_paper',
            field=models.CharField(choices=[('80mm', 'Thermal 80 mm (standard receipt)'), ('58mm', 'Thermal 58 mm (small receipt)'), ('a5', 'A5 page'), ('a4', 'A4 page')], default='80mm', max_length=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='receipt_show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('pta_status', 'PTA Status'), ('device_condition', 'Device Condition'), ('payment_method', 'Payment Methods')], db_index=True, max_length=30)),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('gray', 'Gray')], default='gray', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'id'],
                'unique_together': {('group', 'label')},
            },
        ),
        migrations.RunPython(seed_options, migrations.RunPython.noop),
    ]
