# Generated by Django 4.2.16 on 2026-09-18 17:33

from django.db import migrations, models


def seed_repair_accessories(apps, schema_editor):
    ChoiceOption = apps.get_model('settings_app', 'ChoiceOption')
    for i, label in enumerate(['Charger', 'Back Cover', 'SIM Tray', 'SIM Card',
                               'Memory Card', 'Box', 'Earphones']):
        ChoiceOption.objects.get_or_create(group='repair_accessory', label=label,
                                           defaults={'color': 'gray', 'sort_order': i})


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_companysettings_receipt_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bill_disclaimer',
            field=models.TextField(blank=True, default='کسی بھی کارگو کے ذریعے بھیجے گئے سامان کے نقصان کا دکاندار ذمہ دار نہیں ہوگا۔', help_text='Printed at the bottom of every bill'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='group',
            field=models.CharField(choices=[('pta_status', 'PTA Status'), ('device_condition', 'Device Condition'), ('payment_method', 'Payment Methods'), ('repair_accessory', 'Received With Device (Repairs)')], db_index=True, max_length=30),
        ),
        migrations.RunPython(seed_repair_accessories, migrations.RunPython.noop),
    ]
