# Generated by Django 4.2.16 on 2026-09-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_companysettings_bill_disclaimer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='low_stock_alert_times',
            field=models.CharField(blank=True, default='09:00,11:00', help_text='Times of day the low-stock reminder pops up, e.g. 09:00,11:00', max_length=100),
        ),
    ]
