# Generated by Django 4.2.16 on 2026-09-14 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

TABLE = 'audit_audittrail'


def install_append_only_guards(apps, schema_editor):
    """
    Enforce append-only at the database layer so NO code path — ORM, raw SQL,
    the Django admin, or a manual dbshell — can UPDATE or DELETE an existing row.
    The model/manager guards give friendly Python errors; these triggers are the
    authoritative backstop.
    """
    vendor = schema_editor.connection.vendor
    ex = schema_editor.execute

    if vendor == 'sqlite':
        ex(f"""
            CREATE TRIGGER {TABLE}_no_update
            BEFORE UPDATE ON {TABLE}
            BEGIN
                SELECT RAISE(ABORT, 'AuditTrail is append-only: UPDATE is not allowed');
            END;
        """)
        ex(f"""
            CREATE TRIGGER {TABLE}_no_delete
            BEFORE DELETE ON {TABLE}
            BEGIN
                SELECT RAISE(ABORT, 'AuditTrail is append-only: DELETE is not allowed');
            END;
        """)
    elif vendor == 'postgresql':
        ex(f"""
            CREATE OR REPLACE FUNCTION {TABLE}_block_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'AuditTrail is append-only: % is not allowed', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
        """)
        ex(f"""
            CREATE TRIGGER {TABLE}_no_update
            BEFORE UPDATE ON {TABLE}
            FOR EACH ROW EXECUTE FUNCTION {TABLE}_block_mutation();
        """)
        ex(f"""
            CREATE TRIGGER {TABLE}_no_delete
            BEFORE DELETE ON {TABLE}
            FOR EACH ROW EXECUTE FUNCTION {TABLE}_block_mutation();
        """)
    # Other vendors: model/manager guards still apply; no DB trigger installed.


def remove_append_only_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    ex = schema_editor.execute
    ex(f'DROP TRIGGER IF EXISTS {TABLE}_no_update;')
    ex(f'DROP TRIGGER IF EXISTS {TABLE}_no_delete;')
    if vendor == 'postgresql':
        ex(f'DROP FUNCTION IF EXISTS {TABLE}_block_mutation();')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('inventory_count_modification', 'Inventory count modification'), ('bill_voiding', 'Bill voiding'), ('price_adjustment', 'Price adjustment'), ('manual_stock_adjustment', 'Manual stock adjustment')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=50)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', 'timestamp'], name='audit_audit_action__f8a047_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__318542_idx')],
            },
        ),
        migrations.RunPython(install_append_only_guards, remove_append_only_guards),
    ]
