# Generated by Django 4.2.16 on 2026-09-14 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('display_panel', 'Display Panels & Touch Assemblies'), ('oca_glass', 'OCA Glass & Sheets'), ('battery', 'Batteries & Internal Battery Packs'), ('charging_flex', 'Charging Flex, Strips & Connectors'), ('body_frame', 'Bodies, Frames & Camera Lens Housings'), ('camera_module', 'Camera Modules (Front & Rear)')], db_index=True, max_length=30)),
                ('brand_compat', models.CharField(blank=True, help_text='Compatible phone brand(s), e.g. "Samsung, Oppo"', max_length=100)),
                ('model_compat', models.CharField(blank=True, help_text='Compatible model(s), e.g. "A54, A53, A52"', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_type', models.CharField(blank=True, choices=[('LCD', 'LCD'), ('OLED', 'OLED'), ('AMOLED', 'AMOLED'), ('N/A', 'N/A')], default='N/A', help_text='LCD / OLED / AMOLED — relevant for display_panel category', max_length=10)),
                ('with_frame', models.BooleanField(default=False, help_text='True if the display assembly includes the frame/chassis')),
                ('camera_position', models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear'), ('both', 'Front & Rear'), ('N/A', 'N/A')], default='N/A', help_text='Front / Rear — relevant for camera_module category', max_length=10)),
                ('battery_capacity', models.PositiveIntegerField(blank=True, help_text='mAh — relevant for battery category', null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SparePartLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase', 'Purchase / Stock-In'), ('repair_use', 'Used in Repair'), ('sale', 'Sold to Customer'), ('return_in', 'Return from Customer / Tech'), ('return_out', 'Returned to Supplier'), ('adjustment_in', 'Manual Adjustment (In)'), ('adjustment_out', 'Manual Adjustment (Out)'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('damaged', 'Damaged / Written-Off'), ('testing', 'Used for Testing / Demo')], db_index=True, max_length=20)),
                ('qty', models.IntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost at the time of this movement (for purchase/in entries)', max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, help_text='PO number, repair job number, invoice, etc.', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('balance_after', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='spare_parts.sparepart')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['part', 'created_at'], name='spare_parts_part_id_b60082_idx'), models.Index(fields=['entry_type', 'created_at'], name='spare_parts_entry_t_82e7b5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['category', 'brand_compat'], name='spare_parts_categor_a6e0d6_idx'),
        ),
    ]
