# Generated by Django 4.2.16 on 2026-08-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('discount_threshold', models.DecimalField(decimal_places=2, default=10.0, help_text='Max discount % a cashier can apply without approval', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax rate % for this branch', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
