# Generated by Django 4.2.16 on 2026-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='returned_qty',
            field=models.IntegerField(default=0),
        ),
    ]
