# Generated by Django 4.2.16 on 2026-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoiceline_returned_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('cheque', 'Cheque'), ('installment', 'Installment')], default='cash', max_length=50),
        ),
    ]
