# Generated by Django 4.2.16 on 2026-09-18 17:33

from django.db import migrations, models


def backfill_cost(apps, schema_editor):
    """Past sales didn't store their cost — use today's cost as the best estimate."""
    InvoiceLine = apps.get_model('sales', 'InvoiceLine')
    Product = apps.get_model('inventory', 'Product')
    Unit = apps.get_model('inventory', 'Unit')
    SparePart = apps.get_model('spare_parts', 'SparePart')
    models_by_type = {'unit': Unit, 'spare_part': SparePart}
    for line in InvoiceLine.objects.filter(product_id__isnull=False):
        model = models_by_type.get(line.product_type, Product)
        cost = model.objects.filter(pk=line.product_id).values_list('cost_price', flat=True).first()
        if cost:
            line.cost_price = cost
            line.save(update_fields=['cost_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_unit_condition_alter_unit_pta_status'),
        ('spare_parts', '0001_initial'),
        ('sales', '0003_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_cost, migrations.RunPython.noop),
    ]
