# Generated by Django 4.2.16 on 2026-09-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='item_type',
            field=models.CharField(choices=[('unit', 'Device Unit'), ('product', 'Accessory/Product'), ('spare', 'Spare Part')], max_length=10),
        ),
    ]
